# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: calcul.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'calcul.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x63\x61lcul.proto\x12\x06\x63\x61lcul\"\x1d\n\tnumberRes\x12\x10\n\x08resultat\x18\x01 \x01(\x05\".\n\nnumbersReq\x12\x0f\n\x07number1\x18\x01 \x01(\x05\x12\x0f\n\x07number2\x18\x02 \x01(\x05\x32\xd6\x01\n\rCalculService\x12,\n\x03\x61\x64\x64\x12\x12.calcul.numbersReq\x1a\x11.calcul.numberRes\x12\x32\n\tsubstract\x12\x12.calcul.numbersReq\x1a\x11.calcul.numberRes\x12\x30\n\x07\x64ivided\x12\x12.calcul.numbersReq\x1a\x11.calcul.numberRes\x12\x31\n\x08multiply\x12\x12.calcul.numbersReq\x1a\x11.calcul.numberResb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'calcul_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_NUMBERRES']._serialized_start=24
  _globals['_NUMBERRES']._serialized_end=53
  _globals['_NUMBERSREQ']._serialized_start=55
  _globals['_NUMBERSREQ']._serialized_end=101
  _globals['_CALCULSERVICE']._serialized_start=104
  _globals['_CALCULSERVICE']._serialized_end=318
# @@protoc_insertion_point(module_scope)
