# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import calcul_pb2 as calcul__pb2

GRPC_GENERATED_VERSION = '1.67.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in calcul_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CalculServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.add = channel.unary_unary(
                '/calcul.CalculService/add',
                request_serializer=calcul__pb2.numbersReq.SerializeToString,
                response_deserializer=calcul__pb2.numberRes.FromString,
                _registered_method=True)
        self.substract = channel.unary_unary(
                '/calcul.CalculService/substract',
                request_serializer=calcul__pb2.numbersReq.SerializeToString,
                response_deserializer=calcul__pb2.numberRes.FromString,
                _registered_method=True)
        self.divided = channel.unary_unary(
                '/calcul.CalculService/divided',
                request_serializer=calcul__pb2.numbersReq.SerializeToString,
                response_deserializer=calcul__pb2.numberRes.FromString,
                _registered_method=True)
        self.multiply = channel.unary_unary(
                '/calcul.CalculService/multiply',
                request_serializer=calcul__pb2.numbersReq.SerializeToString,
                response_deserializer=calcul__pb2.numberRes.FromString,
                _registered_method=True)


class CalculServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def add(self, request, context):
        """add 2 numbers
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def substract(self, request, context):
        """sub 2 numbers
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def divided(self, request, context):
        """Add divide 2 numbers
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def multiply(self, request, context):
        """multiply 2 numbers
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CalculServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'add': grpc.unary_unary_rpc_method_handler(
                    servicer.add,
                    request_deserializer=calcul__pb2.numbersReq.FromString,
                    response_serializer=calcul__pb2.numberRes.SerializeToString,
            ),
            'substract': grpc.unary_unary_rpc_method_handler(
                    servicer.substract,
                    request_deserializer=calcul__pb2.numbersReq.FromString,
                    response_serializer=calcul__pb2.numberRes.SerializeToString,
            ),
            'divided': grpc.unary_unary_rpc_method_handler(
                    servicer.divided,
                    request_deserializer=calcul__pb2.numbersReq.FromString,
                    response_serializer=calcul__pb2.numberRes.SerializeToString,
            ),
            'multiply': grpc.unary_unary_rpc_method_handler(
                    servicer.multiply,
                    request_deserializer=calcul__pb2.numbersReq.FromString,
                    response_serializer=calcul__pb2.numberRes.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'calcul.CalculService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('calcul.CalculService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CalculService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def add(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/calcul.CalculService/add',
            calcul__pb2.numbersReq.SerializeToString,
            calcul__pb2.numberRes.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def substract(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/calcul.CalculService/substract',
            calcul__pb2.numbersReq.SerializeToString,
            calcul__pb2.numberRes.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def divided(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/calcul.CalculService/divided',
            calcul__pb2.numbersReq.SerializeToString,
            calcul__pb2.numberRes.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def multiply(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/calcul.CalculService/multiply',
            calcul__pb2.numbersReq.SerializeToString,
            calcul__pb2.numberRes.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
